### ISSUE TITLE
I run "make -j8" after "cmake ../", it shows no makefile?

### ISSUE THREAD

**Issue by hdjsjyl** [kineticadb/kinetica-api-cpp#1]
I run "make -j8" after "cmake ../", it shows no makefile? How to solve this problem?

**Comment by mmahmud** [comment]
Could you please include the commands you used and the errors you're seeing?  Please make sure to install all dependencies and set the appropriate cmake flags (e.g. -DGPUDB_API_CPP_LIBS_DIR).  Thanks!

**Comment by hdjsjyl** [comment]
@mmahmud  , thanks for your reply. Firstly, I am sure of installing all dependencies in /path/project/_build/thirdparty/install, I have changed the value of "-DGPUDB_API_CPP_LIBS_DIR".
Firstly, I build a directory named "build-RelWithDebInfo", and then I input "cmake ../" command in "build-RelWithDebInfo" directory, after that, I input "make -j8", it shows the following error "make: *** No targets specified and no makefile found.  Stop.".

**Comment by hdjsjyl** [comment]
@mmahmud , after "ccmake ../", i get the following information, Can you help me to be sure whether it is successful or not?

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- * ---------------------------------------------------------------------------
-- * CMake general command line options :
-- * 
-- * In the cmake-gui you can set values and press configure a few times 
-- *   until there are no more red items, then press generate.
-- * On the command line set the variables using the -D option.
-- *   Ex: cmake -D[OPTION_NAME]=[OPTION_VALUE] /path/to/CMakeLists.txt/dir/
-- * ---------------------------------------------------------------------------
-- * -DHELP=TRUE 
-- *   Show this help message and exit, no files will be generated.
-- * -DCMAKE_BUILD_TYPE=[Debug, Release, RelWithDebInfo, MinSizeRel] : 
-- *   Makefiles : Set the build type, default is 'RelWithDebInfo'.
-- *   MSVC GUI  : No need to set this since you can choose it in the GUI.
-- * -DBUILD_SHARED_LIBS=[TRUE, FALSE] : (Default static in MSW, shared in Linux)
-- *   Build shared (.dll or .so) or static (.lib or .a) libraries.
-- * ---------------------------------------------------------------------------
--  
-- * No CMAKE_BUILD_TYPE was specified, using default 'RelWithDebInfo'
-- *****************************************************************************
-- * CMAKE_BUILD_TYPE  = RelWithDebInfo
-- * BUILD_SHARED_LIBS = TRUE
-- * Build Arch        = 32-bit FALSE, is 64-bit TRUE
-- * CMAKE_SOURCE_DIR  = /home/lshi/kinetica-api-cpp-master
-- * CMAKE_BINARY_DIR  = /home/lshi/kinetica-api-cpp-master/build-RelWithDebInfo
-- *****************************************************************************
--  
-- * ---------------------------------------------------------------------------
-- * GPUdb API C++ CMake command line options
-- * 
-- * -DGPUDB_API_CPP_LIBS_DIR=/home/lshi/kinetica-api-cpp-master/_build/thirdparty/install
-- *   Specify the location of the 3rd party avro and snappy development libraries.
-- *   Please build them first using the thirdparty/build-thrirdparty-libs.sh script first.
-- *   The install/ dir should contain 'include/' and 'lib/' subdirectories.
-- * 
-- * -DGPUDB_NO_HTTPS=TRUE
-- *   Do not use SSL, else do use it. (Default FALSE)
-- * 
-- * ---------------------------------------------------------------------------
--  
-- * GPUDB_NO_HTTPS = 'FALSE'
-- Found Git: /usr/bin/git (found version "2.7.4") 
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at build/CMakeGitVersion.cmake:29 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:97 (GetGitRepoVersionInfo)


-- * WARNING: cppcheck NOT found, NOT generating ADD_CPPCHECK_TEST() tests
-- *
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- * WARNING: Doxygen NOT found, doxygen target will not be generated.
-- *
-- * GPUDB_API_CPP_LIBS_DIR = '/home/lshi/kinetica-api-cpp-master/_build/thirdparty/install'
-- *
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:151 (find_package)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:151 (find_package)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:151 (find_package)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   regex
-- * Boost_FOUND        = 1
-- * Boost_VERSION      = 106501
-- * Boost_INCLUDE_DIRS = /usr/local/include
-- * Boost_LIBRARY_DIRS = /usr/local/lib
-- * Boost_LIBRARIES    = /usr/local/lib/libboost_system.so;/usr/local/lib/libboost_thread.so;/usr/local/lib/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- *
-- * Compiling with GCC version 5.4.0
-- * Adding gcc warning: -Wlogical-op
-- * COMPILE_DEFS    : 
-- * INCLUDE_DIRS    : /home/lshi/kinetica-api-cpp-master;/home/lshi/kinetica-api-cpp-master/_build/thirdparty/install/include;/usr/local/include
-- * LINK_DIRS       : /usr/lib;/usr/lib64;/home/lshi/kinetica-api-cpp-master/_build/thirdparty/install/lib;/usr/local/lib
-- * CMAKE_CXX_FLAGS :   -Wall -fPIC -fopenmp -rdynamic -D__STDC_LIMIT_MACROS -Wextra -Wformat=2 -Wlogical-op -Wno-deprecated-declarations
-- * NO_QT_CREATOR   : 
-- *
-- * Created  qt-creator config files.
-- *   Usage: qt-creator /home/lshi/kinetica-api-cpp-master/build-RelWithDebInfo/qtcreator-gpudb-api-cpp.creator
-- *
-- * Library targets that can be built from ADD_LIBRARY():
-- * - Boost::diagnostic_definitions
-- * - Boost::disable_autolinking
-- * - Boost::dynamic_linking
-- * - Threads::Threads
-- * - gpudb/gpudb_api_cpp_lib_SHARED
-- * - gpudb/gpudb_api_cpp_lib_STATIC
-- * - Number of libraries: 6
-- * Executable targets that can be built from ADD_EXECUTABLE():
-- * - example/gpudb-api-example
-- * - example/test_multihead_ingest
-- * - Number of executables: 2
-- Configuring incomplete, errors occurred!
See also "/home/lshi/kinetica-api-cpp-master/build-RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "/home/lshi/kinetica-api-cpp-master/build-RelWithDebInfo/CMakeFiles/CMakeError.log".

**Comment by mmahmud** [comment]
@hdjsjyl, it looks like your cmake failed.  Could you please send me the
error log found at
"/home/lshi/kinetica-api-cpp-master/build-RelWithDebInfo/CMakeFiles/CMakeError.log".
Thanks!

**Comment by hdjsjyl** [comment]
@mmahmud , I attach the file in the following:
[CMakeError.log](https://github.com/kineticadb/kinetica-api-cpp/files/2010760/CMakeError.log)
thanks

**Comment by mmahmud** [comment]
Could you please attach the output log as well?  Thanks!

**Comment by hdjsjyl** [comment]
@mmahmud  of course
[CMakeOutput.log](https://github.com/kineticadb/kinetica-api-cpp/files/2010776/CMakeOutput.log)

**Comment by ghost** [comment]
Closing this issue as it is being addressed in 
https://support.kinetica.com/hc/en-us/community/posts/360007645714-Build-kinetica-c-API-on-Linux-failed?page=1#community_comment_360000923934
