### ISSUE TITLE
build cpp-example problem

### ISSUE THREAD

**Issue by hdjsjyl** [kineticadb/kinetica-api-cpp#2]
/usr/bin/ld: CMakeFiles/kinetica.dir/main.cpp.o: undefined reference to symbol 'TLSv1_2_method@@OPENSSL_1.0.1'
//lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/kinetica.dir/build.make:94: recipe for target 'kinetica' failed
gmake[2]: *** [kinetica] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/kinetica.dir/all' failed
gmake[1]: *** [CMakeFiles/kinetica.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2

**Comment by ghost** [comment]
I am closing this issue since it is being addressed in the forum post:
https://support.kinetica.com/hc/en-us/community/posts/360007645714-Build-kinetica-c-API-on-Linux-failed?page=1#community_comment_360000923934
