### ISSUE TITLE
How to delete a table based on cpp API

### ISSUE THREAD

**Issue by hdjsjyl** [kineticadb/kinetica-api-cpp#3]
After filtering the records, it produces a view table. How to delete it? Thanks

**Comment by mmahmud** [comment]
You can use any of the clearTable() functions of GPUdb to delete a table.
https://www.kinetica.com/docs/api/c++/classgpudb_1_1GPUdb.html#a52e2ee9452af707377a8cca0af68320d

The tutorial has an example:
https://www.kinetica.com/docs/tutorials/cpp_guide.html

Thanks!
